---
deployment:
  tasks:
<<<<<<< HEAD
    - export DEPLOYPATH=/home/hcis2460/laravel/
=======
    - export DEPLOYPATH=/home/hcispanel/hc-pm/
>>>>>>> 1762d378f667a96666c64040a2eb1dc3a2e55e9b

    # Copy essential Laravel application directories to deployment path
    - /bin/cp -r app bootstrap config database routes resources $DEPLOYPATH

    # Copy public assets to the public_html directory
<<<<<<< HEAD
    - /bin/cp -r public/assets public/css public/img public/js public/vendor /home/hcis2460/public_html/
=======
    - /bin/cp -r public/assets public/css public/img public/images public/js public/scss public/vendor public/build /home/hcispanel/public_html/hcis.live
>>>>>>> 1762d378f667a96666c64040a2eb1dc3a2e55e9b

    # Change directory to the deployment path
    - cd $DEPLOYPATH

    # Install production dependencies using Composer
    - composer install --no-dev --optimize-autoloader

<<<<<<< HEAD
=======
    # Run database migrations (for first deployment)
    - php artisan migrate --force

>>>>>>> 1762d378f667a96666c64040a2eb1dc3a2e55e9b
    # Clear Laravel application cache
    - php artisan optimize
