deployment:
  tasks:
    - export DEPLOYPATH=/home/hcis2460/laravel/
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r config $DEPLOYPATH
    - /bin/cp -r database $DEPLOYPATH
    - /bin/cp -r routes $DEPLOYPATH
    - /bin/cp -r resources $DEPLOYPATH

    - /bin/cp -r public/* /home/hcis2460/public_html/

    - cd laravel
    - composer install --no-dev --optimize-autoloader

    - php laravel/artisan cache:clear
